### ISSUE TITLE
Config parser is not robust with respect to file encoding

### ISSUE THREAD

**Issue by ShrykeWindgrace** [ennocramer/floskell#3]
When running e.g. `floskell --style cramer --print-config >> floskell.json` in powershell, the output file will be in UTF-16LE (unless you say explicitly that you want utf8). Floskell then fails to parse this file with:
```
floskell.exe: path\to\floskell.json: Error in $: Failed reading: not a valid json value
CallStack (from HasCallStack):
  error, called at src/Floskell\ConfigFile.hs:130:13 in floskell-0.9.0-IXtNWLMqgujDccOHdFWWwn:Floskell.ConfigFile
```
My intuition is that `eitherDecodeStrict ` assumes utf8...

**Comment by ennocramer** [comment]
I'm not sure this issue can be easily fixed, as `aeson` does not support anything but `UTF-8`.  I'm also not sure where the conversion is happening.  It might be powershell (I have no Windows box to test) and thus considered not a bug in Floskell.

This will probably just end up being documented and otherwise left as-is.

**Comment by ShrykeWindgrace** [comment]
Indeed, this is the default behaviour of powershell; I browsed through the docs of `aeson`, it seems that supporting only utf-8 was an explicit choice.
Alas, unless the config parser and/or config format changes, I agree with the option to leave everything as-is and put a remark in readme for powershell users.
