### ISSUE TITLE
Haddock comments on records get misplaced

### ISSUE THREAD

**Issue by mossprescott** [ennocramer/floskell#4]
I wrote this:

```haskell
data Foo = Foo
  { fooBar :: Text
  -- ^A comment, long enough to end up on its own line, or at least I hope so.
  } deriving (Eq)
```

Then ran this and saw the comment get orphaned:

```
$ floskell --style base < FloskellTest.hs 
data Foo = Foo { fooBar :: Text }
-- ^A comment, long enough to end up on its own line, or at least I hope so.
    deriving ( Eq )
```

Without `deriving`, I get this, which does seem to compile, although it's not pretty:
```haskell
data Foo = Foo { fooBar
        :: Text-- ^A comment, long enough to end up on its own line, or at least I hope so.
    }
```

I've tried a number of variations with different results, but I haven't been able to pin down exactly which cause the comment to be moved after the `}`.

**Comment by ennocramer** [comment]
Floskell has a very simple heuristic in deciding whether comments apply to the previous or next AST node. The matter is complicated in this case, as the closing brace is not part of the AST, thus the comment is assigned either to the field declaration (the right choice) or the deriving clause (the wrong choice).

Currently, trailing comments are only considered as such if on the same line as the previous node. Otherwise, they are considered leading comments to the next node.

I have some work in progress to make this decision more intelligent, which should fix this issue, but there will probably always be cases where comments are moved to the wrong position.

**Comment by mossprescott** [comment]
Thanks for the explanation and the fix!
