### ISSUE TITLE
Ambiguous Infix Expression

### ISSUE THREAD

**Issue by ChrisPenner** [ennocramer/floskell#9]
Hey there! Thanks so much for this project, it's pretty much exactly what I've been looking for for a long long time! It was relatively easy to customize the existing configs to mine as well 😄  I especially love that I can run it on subsets of my file easily!

My issue is that I've been getting the following error quite often:

```
floskell: :-1:-1: Ambiguous infix expression
CallStack (from HasCallStack):
  error, called at src/main/Main.hs:147:12 in main:Main
```

I've discovered I can solve it by adding a bunch of brackets around my lens operators, but I was wondering if you had a plan in mind for a more robust way of handling things? Maybe a place where I can specify a list of 'default' fixities for specific unknown operators with maybe a default so that it at least tries to format it in some way, rather than failing completely?

Here's a minimal failing case:

```haskell
thing = funcA . funcB %~ funcC val
```

Thanks for building this, it's a game-changer 😄

**Comment by ennocramer** [comment]
Adding custom fixity declarations is on my todo list. I’ve not had haskell-src-exts fail due to missing fixities before, so i wasn’t aware it was actually a breaking problem. I’ll prioritize that functionality.

**Comment by ChrisPenner** [comment]
Thanks! Keep up the good work 😄

**Comment by ennocramer** [comment]
`master` now has support for custom fixity declarations, either in the config file or on the command line.  The syntax is the same as the fixity declaration in Haskell source, e.g. `"infixr 4 %~"`.

**Comment by AlexeyRaga** [comment]
I am having the same issue when using `master`.
Does it mean that with `floskell` we'd need to add these fixity declarations for all the operators?
The code I try to format uses operators from `lens` and `conduit`, and it'd be very inconvenient to manually work out their fixity and re-introduce them for `floskell`...

**Comment by ennocramer** [comment]
Floskell wants to parse a file without actually looking at its imports, which means it does not have access to the infix declarations of imported packages. At the moment, it knows about all the infix operators in `base`; all other operators need to be declared in `floskell.json`, otherwise Floskell will assume a default fixity/precedence. You can get away with not declaring the fixity, if the operator is only used in expressions where the fixity is unambiguous and/or the wrong precedence does not matter for formatting.

I do plan to include more fixity declarations from popular packages in the default. `lens` and various pipeline packages will definitely be included. For other operators, custom declarations will be required.

**Comment by ennocramer** [comment]
Floskell `master` now has built-in support for `infix` declarations from `aeson`, `conduit`, `lens`, `pipes`, and `servant`.

Do you have any suggestions for other packages that should be supported out of the box?

**Comment by ChrisPenner** [comment]
Not off the top of my head but I'll let you know if any come up 😄 
Thanks!
